# Generated by Django 3.0.6 on 2020-05-18 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_list', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='gender',
            field=models.CharField(default='', max_length=200),
        ),
    ]
