# Generated by Django 3.0.6 on 2020-05-18 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_list', '0003_auto_20200518_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='date',
            field=models.CharField(default='05/18/2020', max_length=200),
        ),
    ]
