# Generated by Django 3.0.6 on 2020-05-18 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_list', '0004_list_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='date',
            field=models.DateField(default='2020-05-18'),
        ),
    ]
