# Generated by Django 3.0.6 on 2020-05-18 04:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('student_list', '0005_auto_20200518_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
