# Generated by Django 3.0.6 on 2020-05-18 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_list', '0006_auto_20200518_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='course',
            field=models.CharField(choices=[('BS Computer Science', 'BS Computer Science'), ('BS Information Technology', 'BS Information Technology'), ('BS Information System', 'BS Information System')], default='BS Computer Science', max_length=200),
        ),
        migrations.AlterField(
            model_name='list',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=200),
        ),
        migrations.AlterField(
            model_name='list',
            name='yearlevel',
            field=models.CharField(choices=[('1st Yr.', '1st Yr.'), ('2nd Yr.', '2nd Yr.'), ('3rd Yr.', '3rd Yr.'), ('4th Yr.', '4th Yr.')], default='1st Yr.', max_length=200),
        ),
    ]
